import { DataSource } from 'typeorm';
import {
  User,
  SeafarerProfile,
  Document,
  Enrollment,
  Course,
  SeaServiceRecord,
  AgentMetadata,
  Company,
  CompanyAdmin,
  CompanyCrew,
  ReferralLead,
  Commission,
  CommissionStatusHistory,
  Invoice,
  Payment,
  Settlement,
  AuditLog,
  PartnerApplication,
  SupportTicket,
  Notification,
  PlatformSettings,
} from './entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.SUPABASE_URL?.replace('https://', '').split('.')[0] || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432', 10),
  username: process.env.DB_USER || 'postgres',
  password: process.env.SUPABASE_DB_PASSWORD || process.env.SUPABASE_SERVICE_ROLE_KEY || 'postgres',
  database: process.env.DB_NAME || 'postgres',
  entities: [
    User,
    SeafarerProfile,
    Document,
    Enrollment,
    Course,
    SeaServiceRecord,
    AgentMetadata,
    Company,
    CompanyAdmin,
    CompanyCrew,
    ReferralLead,
    Commission,
    CommissionStatusHistory,
    Invoice,
    Payment,
    Settlement,
    AuditLog,
    PartnerApplication,
    SupportTicket,
    Notification,
    PlatformSettings,
  ],
  migrations: [__dirname + '/migrations/*{.ts,.js}'],
  synchronize: false,
  logging: true,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});
