import { DataSource, DataSourceOptions } from 'typeorm';
import * as dotenv from 'dotenv';
dotenv.config();

import {
  User,
  SeafarerProfile,
  Document,
  Enrollment,
  Course,
  SeaServiceRecord,
  AgentMetadata,
  Company,
  CompanyAdmin,
  CompanyCrew,
  ReferralLead,
  Commission,
  CommissionStatusHistory,
  Invoice,
  Payment,
  Settlement,
  AuditLog,
  PartnerApplication,
  SupportTicket,
  Notification,
  PlatformSettings,
} from './entities';

const dbOptions: DataSourceOptions = process.env.DATABASE_URL
  ? {
      type: 'postgres',
      url: process.env.DATABASE_URL,
      entities: [
        User,
        SeafarerProfile,
        Document,
        Enrollment,
        Course,
        SeaServiceRecord,
        AgentMetadata,
        Company,
        CompanyAdmin,
        CompanyCrew,
        ReferralLead,
        Commission,
        CommissionStatusHistory,
        Invoice,
        Payment,
        Settlement,
        AuditLog,
        PartnerApplication,
        SupportTicket,
        Notification,
        PlatformSettings,
      ],
      migrations: [__dirname + '/migrations/*{.ts,.js}'],
      synchronize: false,
      logging: true,
      ssl: { rejectUnauthorized: false },
    }
  : {
      type: 'postgres',
      host: process.env.DB_HOST || (process.env.SUPABASE_URL ? `db.${process.env.SUPABASE_URL.replace('https://', '').split('.')[0]}.supabase.co` : 'localhost'),
      port: parseInt(process.env.DB_PORT || '5432', 10),
      username: process.env.DB_USER || 'postgres',
      password: process.env.SUPABASE_DB_PASSWORD || process.env.DB_PASSWORD || 'postgres',
      database: process.env.DB_NAME || 'postgres',
      entities: [
        User,
        SeafarerProfile,
        Document,
        Enrollment,
        Course,
        SeaServiceRecord,
        AgentMetadata,
        Company,
        CompanyAdmin,
        CompanyCrew,
        ReferralLead,
        Commission,
        CommissionStatusHistory,
        Invoice,
        Payment,
        Settlement,
        AuditLog,
        PartnerApplication,
        SupportTicket,
        Notification,
        PlatformSettings,
      ],
      migrations: [__dirname + '/migrations/*{.ts,.js}'],
      synchronize: false,
      logging: true,
      ssl: { rejectUnauthorized: false },
    };

export const AppDataSource = new DataSource(dbOptions);
